### ISSUE TITLE
Can it run on OSX ?

### ISSUE THREAD

**Issue by Gatsby23** [cgtuebingen/pointcloud-viewer#42]

**Comment by Robert42** [comment]
## Short answer
Sadly, no

## Long Answer
The current version is not supported on OS X, as it depends on OpenGL's 4.5 DSA interface, while Apple has sadly decided not to support any OpenGL > 4.2.

There might exist wrappers which wrap Apple's Metal API in an OpenGL 4.5 API (as they do for [OpenGL ES](https://moltengl.com/) and [Vulkan](https://moltengl.com/moltenvk/)), but I am not aware of any such project.

## Future
As development on this project is currently halted (I may decide to reimplement it after I am done with my current project) there won't be an OSX version the foreseeable future.
